CREATE TABLE Bids
(
	  BidID		INTEGER
	, AuctionID	INTEGER NOT NULL
	, BidderID	INTEGER NOT NULL
	, Bid		REAL
	, FOREIGN KEY	(AuctionID) REFERENCES Auctions (AuctionID)
	, FOREIGN KEY	(BidderID) REFERENCES Bidders (BidderID)
	, PRIMARY KEY	(BidID)
)
;
